admins: []
forwards:
- source: -1001575734755
  dest:
  - -1001233550449
  offset: 887
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  filter:
    text:
      blacklist:
      - badword
